#common configuration shared between all applications
configserver:
    name: Docker JHipster Registry
    status: Connected to the JHipster Registry running in Xinerji Test Server 

jhipster:
    security:
        authentication:
            jwt:
                base64-secret: N2Q4ZWNjZjcxYTQwN2QzNjVjNTExNTEwNTZjYjRlZGFjZjI4MzA1NmY1YTU5NjA1OWZlOTgyZTllNjI2YjFmMTM2MjQ0YWQ3Y2QwYTA4OThjODdhOGJhODNmMGVhNzE5MzQ5Nw==
    logging:
        logstash: # forward logs to ELK
            enabled: true
            host: jhipster-logstash
    metrics:
        logs: # report metrics in the logs
            enabled: true
            report-frequency: 60 # in seconds
spring:
    zipkin:
        base-url: http://185.198.199.29:9411
        enabled: true
    sleuth:
        sampler:
            probability: 1 # report 100% of traces to Zipkin

eureka:
    client:
        service-url:
            defaultZone: http://185.198.199.29:8761/eureka/
